version: "3.9"
services:
    db:
        container_name: SearchExtentionsTestDatabase
        build: .
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "MySuperStrongPassword!"
            ACCEPT_EULA: "Y"