name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2

    - name: Test
      run: dotnet test --no-build --verbosity normal

  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        source-url: https://nuget.pkg.github.com/CarlosMorgado/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_KEY}}        
        
    - name: Download Artifacts
      uses: actions/download-artifact@v2

    - name: Build solution and generate NuGet package
      run: dotnet pack -o out

    - name: Push generated package to GitHub registry
      run: dotnet nuget push ./<project>/out/*.nupkg --skip-duplicate --no-symbols true
